// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.AggregatedCounter", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Key")
                        .HasName("PK_HangFire_CounterAggregated");

                    b.HasIndex(new[] { "ExpireAt" }, "IX_HangFire_AggregatedCounter_ExpireAt")
                        .HasFilter("\"ExpireAt\" IS NOT NULL");

                    b.ToTable("AggregatedCounter", "HangFire");
                });

            modelBuilder.Entity("Infrastructure.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ClientId")
                        .HasName("PK__Clients__E67E1A247F564C68");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Infrastructure.Counter", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Key", "Id")
                        .HasName("PK_HangFire_Counter");

                    b.ToTable("Counter", "HangFire");
                });

            modelBuilder.Entity("Infrastructure.Hash", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key", "Field")
                        .HasName("PK_HangFire_Hash");

                    b.HasIndex(new[] { "ExpireAt" }, "IX_HangFire_Hash_ExpireAt")
                        .HasFilter("\"ExpireAt\" IS NOT NULL");

                    b.ToTable("Hash", "HangFire");
                });

            modelBuilder.Entity("Infrastructure.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("InvocationData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("StateId")
                        .HasColumnType("bigint");

                    b.Property<string>("StateName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id")
                        .HasName("PK_HangFire_Job");

                    b.HasIndex(new[] { "ExpireAt" }, "IX_HangFire_Job_ExpireAt")
                        .HasFilter("\"ExpireAt\" IS NOT NULL");

                    b.HasIndex(new[] { "StateName" }, "IX_HangFire_Job_StateName")
                        .HasFilter("\"StateName\" IS NOT NULL");

                    b.ToTable("Job", "HangFire");
                });

            modelBuilder.Entity("Infrastructure.JobParameter", b =>
                {
                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("JobId", "Name")
                        .HasName("PK_HangFire_JobParameter");

                    b.ToTable("JobParameter", "HangFire");
                });

            modelBuilder.Entity("Infrastructure.JobQueue", b =>
                {
                    b.Property<string>("Queue")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("timestamp");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.HasKey("Queue", "Id")
                        .HasName("PK_HangFire_JobQueue");

                    b.ToTable("JobQueue", "HangFire");
                });

            modelBuilder.Entity("Infrastructure.List", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key", "Id")
                        .HasName("PK_HangFire_List");

                    b.HasIndex(new[] { "ExpireAt" }, "IX_HangFire_List_ExpireAt")
                        .HasFilter("\"ExpireAt\" IS NOT NULL");

                    b.ToTable("List", "HangFire");
                });

            modelBuilder.Entity("Infrastructure.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BCFB488B5D6");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Infrastructure.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__D3B9D36CFB411A9A");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Infrastructure.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10, 2)");

                    b.HasKey("ProductId")
                        .HasName("PK__Products__B40CC6CD9448BD62");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Infrastructure.Schema", b =>
                {
                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Version")
                        .HasName("PK_HangFire_Schema");

                    b.ToTable("Schema", "HangFire");
                });

            modelBuilder.Entity("Infrastructure.Server", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("timestamp");

                    b.HasKey("Id")
                        .HasName("PK_HangFire_Server");

                    b.HasIndex(new[] { "LastHeartbeat" }, "IX_HangFire_Server_LastHeartbeat");

                    b.ToTable("Server", "HangFire");
                });

            modelBuilder.Entity("Infrastructure.Set", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("Key", "Value")
                        .HasName("PK_HangFire_Set");

                    b.HasIndex(new[] { "ExpireAt" }, "IX_HangFire_Set_ExpireAt")
                        .HasFilter("\"ExpireAt\" IS NOT NULL");

                    b.HasIndex(new[] { "Key", "Score" }, "IX_HangFire_Set_Score");

                    b.ToTable("Set", "HangFire");
                });

            modelBuilder.Entity("Infrastructure.State", b =>
                {
                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("JobId", "Id")
                        .HasName("PK_HangFire_State");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_HangFire_State_CreatedAt");

                    b.ToTable("State", "HangFire");
                });

            modelBuilder.Entity("Infrastructure.JobParameter", b =>
                {
                    b.HasOne("Infrastructure.Job", "Job")
                        .WithMany("JobParameters")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HangFire_JobParameter_Job");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Infrastructure.Order", b =>
                {
                    b.HasOne("Infrastructure.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("fk_orders_clients");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Infrastructure.OrderDetail", b =>
                {
                    b.HasOne("Infrastructure.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("fk_orderdetails_orders");

                    b.HasOne("Infrastructure.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_orderdetails_products");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Infrastructure.State", b =>
                {
                    b.HasOne("Infrastructure.Job", "Job")
                        .WithMany("States")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HangFire_State_Job");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Infrastructure.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Infrastructure.Job", b =>
                {
                    b.Navigation("JobParameters");

                    b.Navigation("States");
                });

            modelBuilder.Entity("Infrastructure.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Infrastructure.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
